### ISSUE TITLE
db.json back up error?

### ISSUE THREAD

**Issue by YoungsJeong** [swsnu/swpp18-team2#11]
[Wiki](https://github.com/swsnu/swpp18-team2/wiki/realated_urls) 의 1번 url을 참고하여 만들어진 db.json을 load할때 Integrity error가 발생하는데 datadump로 db.json을 만드실때,
  ./manage.py dumpdata --exclude auth.permission --exclude contenttypes > db.json 이 아닌
  ./manage.py dumpdata > db.json의 커맨드를 사용하셨는지요?
  loaddata할때 해당 사이트에 언급된 IntegrityError가 발생하여 여쭙고 싶습니다

**Comment by onteeae** [comment]
우선 오류 발생으로 *.sqlite 파일 자체를 전송함으로써 해결
