### ISSUE TITLE
유효한 비밀번호 판정 기준이 이상한 것 같습니다.

### ISSUE THREAD

**Issue by MountGuy** [swsnu/swpp18-team2#20]
비밀번호로 Merry25^을 시도해 보았는데 받아들여지지 않았습니다. 8자 이상에 알파벳 대문자와 소문자를 분명히 포함하는 비밀번호인데 작동하지 않습니다.

**Comment by onteeae** [comment]
해당 부분은 Validator 정규 표현식에 오류가 있었습니다. 수정하여 Deploy 할 예정입니다.
리뷰 감사합니다.
