### ISSUE TITLE
비밀번호 변경할 때 특수문자가 포함되면 통과가 안됩니다.

### ISSUE THREAD

**Issue by snumath** [swsnu/swpp18-team2#21]
Asdfjkl123같은건 되지만
Asdfjkl123!@#같은건 안됩니다.

**Comment by onteeae** [comment]
#20 와 중복이슈입니다.
해당 부분은 Validator 정규 표현식에 오류가 있었습니다. 수정하여 Deploy 할 예정입니다.
리뷰 감사합니다.
