### ISSUE TITLE
회원 정보 수정 페이지에서 '중복 확인'을 누르면

### ISSUE THREAD

**Issue by hintyu** [swsnu/swpp18-team2#22]
'잘못된 비밀번호 입니다'라고만 뜹니다.

**Comment by onteeae** [comment]
해당 부분은 비밀번호 수정 기능이 아니라 정보 수정시 비밀번호 확인을 위한 입력입니다.
아마 비밀번호 수정이라고 생각하시고 다른 비밀번호를 입력하신 것 같습니다.
리뷰 감사합니다.

**Comment by hintyu** [comment]
이메일(테스트 때는 닉네임이었었나요?) 옆의 '중복 확인' 버튼을 눌렀을 때 비밀번호를 확인하는 패턴이 나오는 게 이상하다고 생각해서 올린 이슈였습니다. 다시 확인해 보니 이슈 문제 없이 잘 작동하네요.
답변 감사합니다. close하셔도 될 것 같네요!

**Comment by onteeae** [comment]
아아 넵 감사합니다!
