### ISSUE TITLE
검색 후 게시글 접속 후 뒤로 갔을 때 검색했던 결과가 모두 사라집니다

### ISSUE THREAD

**Issue by MountGuy** [swsnu/swpp18-team2#23]
검색 창에 키워드를 입력하여 검색을 한 후

결과에서 하나를 선택하여 접속한 뒤

뒤로 버튼으로 돌아갈 경우 검색했던 결과들이 모두 사라져 있습니다.

**Comment by onteeae** [comment]
해당부분은 현재 재현이 안되는데, 아마 리포팅 과정에서 사용자가 많아 API Response가 느려진 것 아닌가 싶습니다.
(사실 이 경우에는 브라우저 캐시가 있어서 Call 없이 캐싱된 검색 결과가 나와야 하는 것이 아닌가 하는 것이 제 추측이긴합니다)
최적화하여 반응속도를 높이는 중에 있습니다.
리뷰 감사합니다.
