### ISSUE TITLE
bug report입니당

### ISSUE THREAD

**Issue by dalbamm** [swsnu/swpp18-team2#25]
team2:
- Too many requests가 뜨면서 웹사이트 접근이 불가능합니다.
- 기본 화면 구성요소 비율이 안좋아서 보기가 불편합니다.
- 태그 후보(선택지)가 드러나는 기능이 있으면 더 편할 것 같습니다.
- 관심사를 누른 후 사이트를 이동할 때 중간에 “존재하지 않는 관심사입니다.”라는 메시지가 일시적으로 뜹니다.

**Comment by onteeae** [comment]
1. 해당 부분은 무료로 사용중인 도메인 서버 문제인 것으로 보입니다.
(ec2~ 도메인 사용시에는 문제 없었습니다.)
2. UI는 최종 발표 전 까지 조금 더 수정해보도록 하겠습니다.
3. 해당 기능은 ' '(space bar) 입력 시 모든 Tag가 보이게 됩니다.
4. #24 와 중복 Issue입니다. Async Pipe 이용하여 수정하도록 하겠습니다.
리뷰 감사합니다.
